obj-$(CONFIG_EXTENDED_LSM) := seccomp.o 
obj-$(CONFIG_SECURITY_AZURE_SPHERE) := udom.o lsm.o fl_list.o fl_netlink.o fl_iface.o difc_fs.o helper.o checker_fs.o
EXTRA_CFLAGS += -Isecurity/azure_sphere/include


